root: /

Home: /

language: en

author: 白菜
description: 笑逐颜开。
# AvatorURL
# it would be shown on sidecar.

avatar: http://q1.qlogo.cn/g?b=qq&nk=2966938704&s=100

# Comment

gitalk:
  enable: true
  clientID: 7a5f44d625d50606a948
  clientSecret: 8218bf5e1400714462f5dedcc59b2acd7cecbcc0
  repo: http://www.n-bc.top
  owner: n-bc
  admin: n-bc

disqus:
  enable: false
  shortname: your_disqus_short_name

# Contact_Info
# Contact info will be shown on the side bar.

contact:
  enable: true
  description: '欢迎来访'

  twitter:
    enable: true
    username: caiyanzhe

  github:
    enable: true
    username: n-bc

  weibo:
    enable: true
    username: yyh2c

  facebook:
    enable: false
    username: facebook_username

  instagram:
    enable: false
    username: instagram_username


# Analytice

## Recommended
umami_analytice:
  enable: false
  website_id: umami_website_id
  js_src: umami_js_src

baidu_analytics:
  enable: false
  id: baidu_analytice_id

google_analytice:
  enable: false
  tracking_id: google_tracking_id

# Website ICPLicense
# which is useful in China mainland.

ICPLicense:
  enable: false
  content: "Fill IPCLicense"

# EtraPlugin

extra_plugin:
  enable: false
  url: extra_plugin_js_url

# Development Setting

node_sass:
  # outputStyle: nested
  outputStyle: compressed
  precision: 5
  sourceComments: false