author: '白菜' # 作者名称
author_avatar: 'http://q.qlogo.cn/headimg_dl?dst_uin=2966938704&spec=640&img_type=jpg' # 作者头像
author_text: '喜欢编程，数码，历史，文具与果茶~嘻嘻' # 作者信息
social: # 社交链接
  
# background: 'https://api.paugram.com/wallpaper?source=gh' # 主题背景
menu: # 页眉菜单项目
  '隐私政策': /about
  '友情链接': /friends
  '开往': https://www.travellings.cn/plain.html
  '虫洞': https://www.foreverblog.cn/go.html
config:
  copyright: true # 复制的时候弹出保留原站链接说明
  night: true # 自动切换夜间模式
