author: 'Hingle' # 作者名称
author_avatar: 'https://sdn.geekzu.org/avatar/d22eb460ecab37fcd7205e6a3c55c228?s=200&r=X&d=' # 作者头像
author_text: '请在这里设置你的作者信息' # 作者信息
social: # 社交链接
  - title: 'Github'
    icon: 'github'
    link: 'https://github.com/caiyanzhe'
  - title: 'Bilibili'
    icon: 'bilibili'
    link: 'https://space.bilibili.com/667817936?spm_id_from=333.1007.0.0'
  - title: '首页'
    icon: 'home'
    link: 'https://www.n-bc.top'
# background: 'https://api.paugram.com/wallpaper?source=gh' # 主题背景
menu: # 页眉菜单项目
  '隐私政策': /about
  '友情链接': /friends
config:
  copyright: true # 复制的时候弹出保留原站链接说明
  night: true # 自动切换夜间模式
