# Header
nav:
  Posts: /archives
  Travelling: https://www.travellings.cn/plain.html
  Friends: /friends
  Categories: /category
  Tags: /tag

# favicon
favicon: http://q1.qlogo.cn/g?b=qq&nk=2966938704&s=100

# logo
logo: http://q1.qlogo.cn/g?b=qq&nk=2966938704&s=100

# links
links:
  Github: https://github.com/n-bc
  # ZhiHu:
  # Twitter:
  # Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable:
  repo:
  repo_id:
  category:
  category_id:
  mapping:

# maple
maple:
  enable: true
  # fall leaf count
  count: 10
  # 0-1
  speed: 0.8

