menu:
    Home: /
    Archives: /archives
    Talk: /talk
    Friends: /friends
    Travelling: https://www.travellings.cn/plain.html
    Forever Blog: https://www.foreverblog.cn/go.html

favicon: favicon.png
logo: favicon.png

# Comment


# Analytics
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2020

# Image Credits
enable_image_credit: true 
